#!/usr/bin/env python

import sys
from hashlib import sha1
from base64 import urlsafe_b64encode as b64enc

if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit("Usage: %s url" % sys.argv[0])
    print b64enc(sha1(sys.argv[1]).digest())
